# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('mobile', models.TextField()),
                ('DOB', models.TextField()),
                ('Flag', models.CharField(max_length=1)),
                ('ORG', models.TextField()),
            ],
        ),
    ]
