# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='DOB',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='ORG',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
