# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170322_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Email_ID',
        ),
    ]
